### PR TITLE
Cache only GET request without authorization

### PR DESCRIPTION
**Pull request by radeno**

### CODE REVIEW

**Comment by airesvsg** [comment]
Hi, 

Can you explain what's happened?

Thanks

**Comment by radeno** [comment]
Hi, i think my PR was buggy. Some request was cached and should not be.

Anyway i start using another plugin i don't want to introduce new bugs with my PR.

Thank you for work you do on this module.

**Comment by airesvsg** [comment]
Thanks for your answer.

The plugin not will cause any bug in your PR, because all cache is stored in database, please review your application.

Thanks again

**Comment by radeno** [comment]
We dont use database as cache. Thanks anyway

**Comment by airesvsg** [comment]
My plugin use transient api, it use database to store the cache.

**Comment by radeno** [comment]
I know, we are using it with combination of Redis.
But still, sometimes my PR makes some POST requests to be cached. What is weird.
That was the point i closed my PR.

**Pull request closed without merging**
